
version: "3"

services:
  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_No_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=1

